site_name: SC Mesh
site_url: https://www.sc-mesh.org
repo_url: https://github.com/scmesh/scmesh.github.io/


theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - search.share
  icon:
    logo: fontawesome/solid/circle-nodes
  favicon: img/favicon.png

nav:
  - Home: index.md
  - Primeiros Passos: primeiros-passos.md
  - Comunidade: comunidade-governanca.md
  - Hardware: hardware.md
  - Infraestrutura: infraestrutura.md
  - Wiki Técnica: wiki-tecnica.md
  - Recursos: recursos.md