site_name: SC Mesh
site_url: https://www.sc-mesh.org
repo_url: https://github.com/scmesh/scmesh.github.io/


theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/console
        name: Switch to dark mode
  features:
    - navigation.tabs
    - search.share
  icon:
    logo: fontawesome/solid/circle-nodes
  favicon: img/favicon.png

plugins:
  - search
  - blog:
      authors_profiles: true
      blog_toc: true

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Primeiros Passos: primeiros-passos.md
  - Hardware: hardware.md
  - Infraestrutura: infraestrutura.md
  - Emergência: emergencia.md
  - Segurança e Privacidade: seguranca-privacidade.md
  - Casos de Uso: casos-de-uso.md
  - Comunidade:
      - Visão e governança: comunidade-governanca.md
      - Eventos: eventos.md
      - Vaquinhas e financiamento: financiamento.md
      - Galeria de setups: galeria.md
      - Para radioamadores: radioamadores.md
      - Relatórios pós-evento: relatorios.md
      - Código de conduta: codigo-de-conduta.md
      - Como contribuir: contribuindo.md
  - Wiki Técnica: wiki-tecnica.md
  - FAQ: faq.md
  - Glossário: glossario.md
  - Ferramentas: ferramentas.md
  - Recursos: recursos.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
